apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - mysql.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: medical-backend
    newName: ghcr.io/shimamurahougetsu1337/medical-asset-maintenance-system-backend
    newTag: latest
  - name: medical-frontend
    newName: ghcr.io/shimamurahougetsu1337/medical-asset-maintenance-system-frontend
    newTag: latest
